#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const DICT = path.join(ROOT, 'scrabble_dictionary.txt');
const FREQ = path.join(ROOT, 'word_frequency.csv');
const OUT = path.join(ROOT, 'data.js');

const words = fs
  .readFileSync(DICT, 'utf8')
  .split('\n')
  .map(w => w.trim().toLowerCase())
  .filter(w => /^[a-z]{5}$/.test(w));

const freq = {};
for (const line of fs.readFileSync(FREQ, 'utf8').split('\n')) {
  const idx = line.lastIndexOf(',');
  if (idx <= 0) continue;
  const word = line.slice(0, idx).trim().toLowerCase();
  const count = parseInt(line.slice(idx + 1).trim(), 10);
  if (!/^[a-z]{5}$/.test(word) || !Number.isFinite(count)) continue;
  if (count > (freq[word] || 0)) freq[word] = count;
}

const scored = words.filter(w => freq.hasOwnProperty(w));

const payload = {
  WORDS: words,
  FREQ: Object.fromEntries(scored.map(w => [w, freq[w]]))
};

const banner =
  '// Auto-generated by build_data.js from scrabble_dictionary.txt and word_frequency.csv.\n' +
  '// Do not edit by hand. Regenerate with: node build_data.js\n';
fs.writeFileSync(OUT, banner + 'window.WORDLE_DATA = ' + JSON.stringify(payload) + ';\n');

console.log(`dictionary 5-letter words: ${words.length}`);
console.log(`frequency 5-letter words:  ${Object.keys(freq).length}`);
console.log(`usable guess words (kept): ${words.length}`);
console.log(`words with frequency:      ${scored.length}`);
console.log(`wrote ${OUT} (${(fs.statSync(OUT).size / 1024).toFixed(0)} KB)`);